"""add invoice templates and sale invoice pdf path

Revision ID: 1ae783f7c9c1
Revises: 43bf8e3f4590
Create Date: 2026-08-07 18:39:57.725403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae783f7c9c1'
down_revision: Union[str, Sequence[str], None] = '43bf8e3f4590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_templates_tenant_id'), 'invoice_templates', ['tenant_id'], unique=True)
    op.add_column('sales', sa.Column('invoice_pdf_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'invoice_pdf_path')
    op.drop_index(op.f('ix_invoice_templates_tenant_id'), table_name='invoice_templates')
    op.drop_table('invoice_templates')
    # ### end Alembic commands ###
