"""add business_id to tenants

Revision ID: 43bf8e3f4590
Revises: 9dbbc4ee9bb1
Create Date: 2026-08-07 15:43:57.106728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43bf8e3f4590'
down_revision: Union[str, Sequence[str], None] = '9dbbc4ee9bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('business_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_tenants_business_id'), 'tenants', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_business_id'), table_name='tenants')
    op.drop_column('tenants', 'business_id')
    # ### end Alembic commands ###
