"""sale_item_shelf_id_nullable

Revision ID: 4ed64248fc5c
Revises: d275f746d875
Create Date: 2026-07-31 02:20:15.736066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed64248fc5c'
down_revision: Union[str, Sequence[str], None] = 'd275f746d875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_items', 'shelf_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_items', 'shelf_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
