"""shelfitem_timestamps_category_updated_at

Revision ID: 5808030f8c66
Revises: b714d6690000
Create Date: 2026-07-25 12:25:05.679933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5808030f8c66'
down_revision: Union[str, Sequence[str], None] = 'b714d6690000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('shelf_items', sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('shelf_items', sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelf_items', 'updatedAt')
    op.drop_column('shelf_items', 'createdAt')
    op.drop_column('categories', 'updatedAt')
    # ### end Alembic commands ###
