"""pos_payments_cash_register_stations_pin

Revision ID: 5ea3fec9582f
Revises: 873746532450
Create Date: 2026-08-03 22:21:39.254186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea3fec9582f'
down_revision: Union[str, Sequence[str], None] = '873746532450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE', name='station_status'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_station_tenant_code')
    )
    op.create_index(op.f('ix_stations_tenant_id'), 'stations', ['tenant_id'], unique=False)
    op.create_table('cash_register_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opening_amount', sa.Float(), nullable=False),
    sa.Column('closing_amount', sa.Float(), nullable=True),
    sa.Column('expected_cash', sa.Float(), nullable=True),
    sa.Column('discrepancy', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='cash_register_status'), nullable=False),
    sa.Column('opened_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_register_sessions_tenant_id'), 'cash_register_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cash_register_sessions_user_id'), 'cash_register_sessions', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'WALLET', 'OTHER', name='payment_method'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_sale_id'), 'payments', ['sale_id'], unique=False)
    op.create_table('station_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=30), nullable=True),
    sa.Column('customer_document', sa.String(length=30), nullable=True),
    sa.Column('customer_address', sa.String(length=500), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='session_status'), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('openedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_sessions_created_by'), 'station_sessions', ['created_by'], unique=False)
    op.create_index(op.f('ix_station_sessions_customer_id'), 'station_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_station_sessions_sale_id'), 'station_sessions', ['sale_id'], unique=False)
    op.create_index(op.f('ix_station_sessions_station_id'), 'station_sessions', ['station_id'], unique=False)
    op.create_table('station_session_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PREPARING', 'READY', 'DELIVERED', 'CANCELLED', name='session_item_status'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['station_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_session_items_product_id'), 'station_session_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_station_session_items_session_id'), 'station_session_items', ['session_id'], unique=False)
    op.add_column('sales', sa.Column('payment_status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False))
    op.add_column('users', sa.Column('pin', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin')
    op.drop_column('sales', 'payment_status')
    op.drop_index(op.f('ix_station_session_items_session_id'), table_name='station_session_items')
    op.drop_index(op.f('ix_station_session_items_product_id'), table_name='station_session_items')
    op.drop_table('station_session_items')
    op.drop_index(op.f('ix_station_sessions_station_id'), table_name='station_sessions')
    op.drop_index(op.f('ix_station_sessions_sale_id'), table_name='station_sessions')
    op.drop_index(op.f('ix_station_sessions_customer_id'), table_name='station_sessions')
    op.drop_index(op.f('ix_station_sessions_created_by'), table_name='station_sessions')
    op.drop_table('station_sessions')
    op.drop_index(op.f('ix_payments_sale_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_cash_register_sessions_user_id'), table_name='cash_register_sessions')
    op.drop_index(op.f('ix_cash_register_sessions_tenant_id'), table_name='cash_register_sessions')
    op.drop_table('cash_register_sessions')
    op.drop_index(op.f('ix_stations_tenant_id'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
