"""cleanup_remove_api_key_and_discontinued

Revision ID: 6c9f138aa0d0
Revises: 5ea3fec9582f
Create Date: 2026-08-03 23:02:43.789737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9f138aa0d0'
down_revision: Union[str, Sequence[str], None] = '5ea3fec9582f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_key', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
