"""taxes_customers_tenant_settings

Revision ID: 873746532450
Revises: f0bdc2008ef4
Create Date: 2026-07-31 11:38:10.213320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873746532450'
down_revision: Union[str, Sequence[str], None] = 'f0bdc2008ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('document', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_document'), 'customers', ['document'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('taxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tax_tenant_name')
    )
    op.create_index(op.f('ix_taxes_tenant_id'), 'taxes', ['tenant_id'], unique=False)
    op.create_table('product_taxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_id'], ['taxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'tax_id', name='uq_product_tax')
    )
    op.create_index(op.f('ix_product_taxes_product_id'), 'product_taxes', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_taxes_tax_id'), 'product_taxes', ['tax_id'], unique=False)
    op.add_column('orders', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('customer_document', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('customer_address', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.add_column('sale_items', sa.Column('tax_amount', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('sales', sa.Column('customer_phone', sa.String(length=30), nullable=True))
    op.add_column('sales', sa.Column('customer_document', sa.String(length=30), nullable=True))
    op.add_column('sales', sa.Column('customer_address', sa.String(length=500), nullable=True))
    op.add_column('sales', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.add_column('tenants', sa.Column('api_key', sa.String(length=64), nullable=True))
    op.add_column('tenants', sa.Column('logo_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'logo_path')
    op.drop_column('tenants', 'api_key')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_column('sales', 'customer_id')
    op.drop_column('sales', 'customer_address')
    op.drop_column('sales', 'customer_document')
    op.drop_column('sales', 'customer_phone')
    op.drop_column('sales', 'customer_email')
    op.drop_column('sale_items', 'tax_amount')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_column('orders', 'customer_id')
    op.drop_column('orders', 'customer_address')
    op.drop_column('orders', 'customer_document')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'customer_email')
    op.drop_index(op.f('ix_product_taxes_tax_id'), table_name='product_taxes')
    op.drop_index(op.f('ix_product_taxes_product_id'), table_name='product_taxes')
    op.drop_table('product_taxes')
    op.drop_index(op.f('ix_taxes_tenant_id'), table_name='taxes')
    op.drop_table('taxes')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_document'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
