"""add cash register FK to sales orders stations

Revision ID: 9dbbc4ee9bb1
Revises: e614c0148781
Create Date: 2026-08-07 15:18:47.261332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dbbc4ee9bb1'
down_revision: Union[str, Sequence[str], None] = 'e614c0148781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_register_sessions', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('cash_register_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_cash_register_id'), 'orders', ['cash_register_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'cash_register_sessions', ['cash_register_id'], ['id'], ondelete='SET NULL')
    op.add_column('sales', sa.Column('cash_register_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_cash_register_id'), 'sales', ['cash_register_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'cash_register_sessions', ['cash_register_id'], ['id'], ondelete='SET NULL')
    op.add_column('station_sessions', sa.Column('cash_register_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_station_sessions_cash_register_id'), 'station_sessions', ['cash_register_id'], unique=False)
    op.create_foreign_key(None, 'station_sessions', 'cash_register_sessions', ['cash_register_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_station_sessions_cash_register_id'), table_name='station_sessions')
    op.drop_column('station_sessions', 'cash_register_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_cash_register_id'), table_name='sales')
    op.drop_column('sales', 'cash_register_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_cash_register_id'), table_name='orders')
    op.drop_column('orders', 'cash_register_id')
    op.drop_column('cash_register_sessions', 'name')
    # ### end Alembic commands ###
