"""add_updated_at

Revision ID: edac90b06e7e
Revises: 
Create Date: 2026-07-24 15:54:51.518233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edac90b06e7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('updateAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updatedAt')
    op.drop_column('roles', 'updatedAt')
    op.drop_column('products', 'updateAt')
    # ### end Alembic commands ###
