"""multitenant_tenant_id

Revision ID: f0bdc2008ef4
Revises: 8cbbf815162e
Create Date: 2026-07-31 09:06:38.661883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0bdc2008ef4'
down_revision: Union[str, Sequence[str], None] = '8cbbf815162e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('categories', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_category_tenant_name', 'categories', ['tenant_id', 'name'])
    op.create_foreign_key(None, 'categories', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('events', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'events', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_product_tenant_barcode', 'products', ['tenant_id', 'barcode'])
    op.create_foreign_key(None, 'products', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('roles', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_role_tenant_name', 'roles', ['tenant_id', 'name'])
    op.create_foreign_key(None, 'roles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('sales', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_sales_tenant_id'), 'sales', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('shelves', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('shelves_code_key'), 'shelves', type_='unique')
    op.create_index(op.f('ix_shelves_tenant_id'), 'shelves', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_shelf_tenant_code', 'shelves', ['tenant_id', 'code'])
    op.create_foreign_key(None, 'shelves', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'shelves', type_='foreignkey')
    op.drop_constraint('uq_shelf_tenant_code', 'shelves', type_='unique')
    op.drop_index(op.f('ix_shelves_tenant_id'), table_name='shelves')
    op.create_unique_constraint(op.f('shelves_code_key'), 'shelves', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('shelves', 'tenant_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_tenant_id'), table_name='sales')
    op.drop_column('sales', 'tenant_id')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint('uq_role_tenant_name', 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('roles', 'tenant_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint('uq_product_tenant_barcode', 'products', type_='unique')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.drop_column('products', 'tenant_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_column('orders', 'tenant_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_column('events', 'tenant_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint('uq_category_tenant_name', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'tenant_id')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
