from enum import Enum


class PermissionCode(str, Enum):
    PRODUCTS_CREATE = "products_create"
    PRODUCTS_READ = "products_read"
    PRODUCTS_UPDATE = "products_update"
    PRODUCTS_DELETE = "products_delete"
    EVENTS_READ = "events_read"
    ROLES_MANAGE = "roles_manage"
    USERS_MANAGE = "users_manage"
    SHELVES_CREATE = "shelves_create"
    SHELVES_READ = "shelves_read"
    SHELVES_UPDATE = "shelves_update"
    SHELVES_DELETE = "shelves_delete"
    CATEGORIES_CREATE = "categories_create"
    CATEGORIES_READ = "categories_read"
    CATEGORIES_UPDATE = "categories_update"
    CATEGORIES_DELETE = "categories_delete"
    SALES_CREATE = "sales_create"
    SALES_READ = "sales_read"
    ORDERS_CREATE = "orders_create"
    ORDERS_READ = "orders_read"
    ORDERS_MANAGE = "orders_manage"
    TENANTS_MANAGE = "tenants_manage"
    TAXES_MANAGE = "taxes_manage"
    TAXES_READ = "taxes_read"
    CUSTOMERS_READ = "customers_read"
    CUSTOMERS_MANAGE = "customers_manage"
    PAYMENTS_READ = "payments_read"
    PAYMENTS_MANAGE = "payments_manage"
    SALES_CANCEL = "sales_cancel"
    STATIONS_READ = "stations_read"
    STATIONS_MANAGE = "stations_manage"
    CASH_REGISTER_READ = "cash_register_read"
    CASH_REGISTER_MANAGE = "cash_register_manage"
